# Audio Transcription Controller v2 Configuration

# WebSocket server URL
ws_url = "ws://150.1.6.144:6790"

# PDF monitoring directory
pdf_dir = "./pdf_for_submission"

# HTTP API server settings
http_host = "127.0.0.1"
http_port = 9001

# Hotkey bindings
hotkey_stop = "f1"
hotkey_check_pdf = "f2"

# PDF settings
pdf_glob = "*.pdf"
pdf_wait_window_s = 5

# WebSocket reconnection settings
reconnect_base_s = 0.5
reconnect_max_s = 15.0

